[window]
padding = { x = 12, y = 12 }
decorations = "full"
opacity = 0.95
startup_mode = "Windowed"
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13
offset = { x = 0, y = 2 }

[cursor]
style = { shape = "Beam", blinking = "Always" }

[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

[colors.cursor]
text = '#282a36'
cursor = '#f8f8f2'

[colors.normal]
black = '#000000'
red = '#ff5555'
green = '#50fa7b'
yellow = '#f1fa8c'
blue = '#bd93f9'
magenta = '#ff79c6'
cyan = '#8be9fd'
white = '#bfbfbf'

[colors.bright]
black = '#4d4d4d'
red = '#ff6e67'
green = '#5af78e'
yellow = '#f4f99d'
blue = '#caa9fa'
magenta = '#ff92d0'
cyan = '#9aedfe'
white = '#e6e6e6'

[selection]
save_to_clipboard = true

[terminal]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/home/cgreid/.local/bin/xonsh"
args = ["--login"]

#[terminal.shell]
#program = "/home/cgreid/.local/bin/xonsh"
#args = ["--login"]
